### PR TITLE
Fix list renderer to respect original content

### LINKED ISSUE #12: Rework `ListBlockRenderer` and `ListItemRenderer` to respect node settings
As discussed in #9 and #10, the package currently does a poor job at respecting the various node settings available in the renderer.

We should refactor both `ListBlockRenderer` and `ListItemRenderer` to respect the available node settings and support various list types.

```md
- List Item
- Lst Item
```

```md
* List Item
* List Item
```

```md
1. List Item
2. List Item
```

```md
1) List Item
2) List Item
```

If possible, it would also be great if we could remove our workaround for multi-line list items we've added in #7 that temporarily adds the string `_COMMONMARK_MARKDOWN_RENDERER_LINE_BREAK_` to list items.

### PR DESCRIPTION
**Pull request by GuySartorelli**
Fixes #12

List items are now responsible for adding appropriate padding and setting the correct list type, which matches the original source.

I gave this a go with nested lists - the kitchen sink failed that, but it fails in the same (or at least a similar) way for the existing code so I don't think that's a degradation. In both scenarios it can't figure out what level of padding it should give the nested lists, and sometimes adds extra lines. I've raised https://github.com/stefanzweifel/commonmark-markdown-renderer/issues/13 to track fixing that separately.

Note that this still fails `ListBlockRendererTest`  - I don't understand what the intention of the `::children::` placeholders are so I didn't touch those tests.

### CODE REVIEW

File: src/Renderer/Block/ListBlockRenderer.php [hunk 1]
```diff
@@ -21,39 +21,9 @@ public function render(Node $node, ChildNodeRendererInterface $childRenderer): s
...
-
-        if ($listData->type === ListBlock::TYPE_ORDERED) {
-            $returnArray = [];
-            foreach ($content as $key => $value) {
-                $key++;
-                $returnArray[] = "{$key}. $value";
-            }
-
-            $content = $returnArray;
-        }
```
Comment (GuySartorelli) [inline src/Renderer/Block/ListBlockRenderer.php:43]: Each list item has enough information to correctly handle this themselves

File: src/Renderer/Block/ListBlockRenderer.php [hunk 2]
```diff
@@ -21,39 +21,9 @@ public function render(Node $node, ChildNodeRendererInterface $childRenderer): s
...
-     * Replace custom line break character with _native_ line breaks.
-     * Whitespace is added so that other Markdown clients correctly
-     * render the list and its line breaks.
-     * @param string $content
-     * @return string
-     */
-    private function replaceInternalLineBreakCharacter(string $content): string
-    {
-        return str_replace(ListItemRenderer::INLINE_LINE_BREAK, "   \n  ", $content);
-    }
```
Comment (GuySartorelli) [inline src/Renderer/Block/ListBlockRenderer.php:58]: The list items already know what padding they should be adding, so let them handle it.

File: tests/Renderer/Block/ListBlockRendererTest.php
Comment (stefanzweifel) [inline tests/Renderer/Block/ListBlockRendererTest.php:1]: The tests have been updated to build the AST itself and no longer rely on `FakeChildNodeRenderer`.

**Review by stefanzweifel — APPROVED** [review]
Thanks for putting in the work here @GuySartorelli! ❤️ 

I've fixed the tests by passing the a correct AST to the renderer, so we don't have to rely on `FakeChildNodeRenderer`.

If you don't have anything else to add, I would merge this PR.

**Comment by GuySartorelli** [comment]
Sweet. If you're happy with it, I'm happy with it.
